"""Project settings"""

import datetime as dt
from pathlib import Path


PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
DATA_DIR_SRC = DATA_DIR / "raw"
DATA_DIR_PROCESSED = DATA_DIR / "clean"
DATA_DIR_PUBLIC = DATA_DIR / "public"

INDOOR_LOCATIONS = [
    "APARTMENT", "RESIDENCE", "HOUSE", "GAS STATION", "RESTAURANT",
    "CHA APARTMENT", "HALLWAY", "RETAIL STORE", "ABANDONED BUILDING",
    "GARAGE", "CHA HALLWAY", "TAVERN", "HOSPITAL BUILDING / GROUNDS",
    "BAR OR TAVERN", "BASEMENT", "SMALL RETAIL STORE", "CONVENIENCE STORE",
    "BARBER SHOP/BEAUTY SALON", "OFFICE", "VESTIBULE", "LIQUOR STORE",
    "HOSPITAL BUILDING/GROUNDS", "CHA LOBBY", "CLUB", "BARBERSHOP",
    "CTA BUS", "STAIRWELL", "CTA STAIRWELL", "CAR WASH", "COMMERCIAL / BUSINESS OFFICE",
    "MOTEL", "GROCERY FOOD STORE", "HOSPITAL", "RESIDENCE - GARAGE", "TRUCK",
    "TAVERN/LIQUOR STORE", "CTA TRAIN", "HOTEL / MOTEL", 'CTA "L" TRAIN',
    "VEHICLE-COMMERCIAL", "GARAGE/AUTO REPAIR", "WAREHOUSE", "TAVERN / LIQUOR STORE",
    "NURSING HOME", "CHURCH", "COUNTY JAIL", "CHA HALLWAY / STAIRWELL / ELEVATOR",
    "CHA ELEVATOR", "CURRENCY EXCHANGE", "BANK", "CHA HALLWAY/STAIRWELL/ELEVATOR",
    "CLEANERS/LAUNDROMAT", "ROOMING HOUSE", "FACTORY", "DEPARTMENT STORE",
    "TAXICAB", "TRAILER", "BANQUET HALL", "LIVERY STAND OFFICE",
    "GOVERNMENT BUILDING / PROPERTY", "VEHICLE - OTHER RIDE SERVICE",
    "OTHER COMMERCIAL TRANSPORTATION", "VEHICLE - COMMERCIAL", "GAME ROOM",
    "CTA SUBWAY STATION", "LAUNDRY ROOM", "PUBLIC GRAMMAR SCHOOL",
    "YMCA", "DAY CARE CENTER", "PUBLIC HIGH SCHOOL", "ELEVATOR", "CLEANING STORE",
    "VEHICLE - COMMERCIAL: ENTERTAINMENT / PARTY BUS", "POLICE FACILITY",
    "GOVERNMENT BUILDING", "HOTEL/MOTEL", "COACH HOUSE", "POOLROOM",
    "VEHICLE - OTHER RIDE SHARE SERVICE (LYFT, UBER, ETC.)", "SCHOOL, PUBLIC, BUILDING",
    "CTA GARAGE / OTHER PROPERTY", "TRAILER HOME", "RAILROAD TRAIN", "COURT HOUSE",
    "TRUCKING TERMINAL", "DRUG STORE", "BETTING PARLOR", "SPORTS ARENA / STADIUM",
    "CHURCH/SYNAGOGUE/PLACE OF WORSHIP", "VEHICLE NON-COMMERCIAL",
    "VEHICLE - OTHER RIDE SHARE SERVICE (E.G., UBER, LYFT)",
    "SCHOOL, PRIVATE, BUILDING", "RELIEF SHELTER", "FUNERAL PARLOR",
    "CHA TOWNHOUSE", "LIVERY AUTO", "NURSING / RETIREMENT HOME", "AUTO",
    "CHURCH HALL", "GOVERNMENT BUILDING/PROPERTY", "NURSING HOME/RETIREMENT HOME",
    "APPLIANCE STORE", "LIBRARY", "MOVIE HOUSE / THEATER", "ATHLETIC CLUB",
    "BOWLING ALLEY", "MEDICAL / DENTAL OFFICE", "CHURCH / SYNAGOGUE / PLACE OF WORSHIP",
    "SCHOOL - PUBLIC BUILDING", "COLLEGE/UNIV. BUILDING", "PAWN SHOP", "FIRE STATION",
    "RESIDENCE PORCH/HALLWAY", "RESIDENCE - PORCH / HALLWAY", "RESIDENCE-GARAGE",
    "HOTEL", "TAXI CAB", "CHA STAIRWELL", "RESIDENCE PORCH/HALLWAY", "RESIDENCE - PORCH / HALLWAY",
    "RESIDENCE-GARAGE", "PARKING LOT/GARAGE(NON.RESID.)", "PARKING LOT / GARAGE (NON RESIDENTIAL)",
]
SHOTSPOTTER_DISTRICTS = [
    "025", "015", "011", "010", "009", "002", "008", "007", "003", "006", "004", "005",
]
SEARCH_RADIUS_IN_METERS = 0.5 * 1609.34
TIME_WINDOW = dt.timedelta(hours=1)
